[build]
  publish = "build/web"
  command = """
    export FLUTTER_VERSION=3.24.3
    git clone https://github.com/flutter/flutter.git -b stable --depth 1
    export PATH="$PATH:`pwd`/flutter/bin"
    flutter config --enable-web
    flutter build web
  """